-- Catálogo nível 2 (avançado) — tweaks reais de rede/resposta do sistema,
-- serviços não essenciais e tarefas de telemetria — agora que o motor de
-- perfis sabe de fato aplicar service_set_start_type e scheduled_task_disable
-- (antes só existiam no protocolo/Serviço, sem orquestração).

INSERT INTO optimizations (
    id, nome, categoria, descricao, objetivo, beneficio_esperado, risco,
    requer_administrador, requer_reinicializacao,
    caminho, nome_do_valor, tipo_do_valor, valor_recomendado,
    comando_de_aplicacao, comando_de_reversao, fonte_tecnica
) VALUES
(
    'opt-network-throttling-off',
    'Desativar limitação de rede para multimídia/jogos',
    'network',
    'Remove o limite de banda que o Windows aplica a processos não-multimídia quando um app multimídia está em primeiro plano.',
    'Reduzir latência de rede em jogos e apps de tempo real.',
    'Menos throttling de pacotes de rede sob carga; efeito mais perceptível em conexões já congestionadas.',
    'advanced', 1, 0,
    'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile',
    'NetworkThrottlingIndex',
    'REG_DWORD',
    '4294967295',
    'registry_set_dword',
    'registry_restore_value',
    'Microsoft Learn — Multimedia Class Scheduler Service (MMCSS) NetworkThrottlingIndex'
),
(
    'opt-system-responsiveness',
    'Reduzir reserva de CPU para tarefas em segundo plano (MMCSS)',
    'registry',
    'Reduz a porcentagem de CPU que o MMCSS reserva para tarefas de baixa prioridade, priorizando o app em foco.',
    'Dar mais CPU ao jogo/app ativo em vez de tarefas de segundo plano.',
    'Mais CPU disponível para o processo em foco sob carga; pode aumentar levemente a latência de tarefas de segundo plano.',
    'advanced', 1, 0,
    'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile',
    'SystemResponsiveness',
    'REG_DWORD',
    '0',
    'registry_set_dword',
    'registry_restore_value',
    'Microsoft Learn — MMCSS SystemResponsiveness'
),
(
    'opt-win32-priority-separation',
    'Priorizar aplicativo em primeiro plano (agendador de CPU)',
    'registry',
    'Ajusta o Win32PrioritySeparation para dar rajadas de CPU maiores e mais longas ao processo em primeiro plano.',
    'Reduzir engasgos no app/jogo ativo quando há muitos processos em segundo plano.',
    'Resposta mais consistente do app em foco; processos em segundo plano recebem menos fatias de CPU.',
    'advanced', 1, 0,
    'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\PriorityControl',
    'Win32PrioritySeparation',
    'REG_DWORD',
    '38',
    'registry_set_dword',
    'registry_restore_value',
    'Microsoft Learn — Win32PrioritySeparation (agendamento de threads)'
),
(
    'opt-games-gpu-priority',
    'Prioridade máxima de GPU para jogos',
    'gaming',
    'Define a prioridade de GPU mais alta possível para a categoria de tarefa "Games" do agendador multimídia.',
    'Reduzir a chance de outro processo (captura de tela, navegador) roubar ciclos de GPU do jogo.',
    'GPU dedicada preferencialmente ao jogo em primeiro plano.',
    'advanced', 1, 0,
    'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\Games',
    'GPU Priority',
    'REG_DWORD',
    '8',
    'registry_set_dword',
    'registry_restore_value',
    'Microsoft Learn — MMCSS Games task GPU Priority'
),
(
    'opt-disable-telemetry-policy',
    'Reduzir telemetria do Windows ao mínimo (política de grupo)',
    'registry',
    'Define a política AllowTelemetry como 0 (nível mínimo/segurança), reduzindo dados enviados à Microsoft.',
    'Reduzir uso de rede/disco em segundo plano por coleta de diagnóstico.',
    'Menos atividade de rede/disco em segundo plano; disponível apenas em edições Enterprise/Education para nível 0 ter efeito completo.',
    'advanced', 1, 0,
    'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\DataCollection',
    'AllowTelemetry',
    'REG_DWORD',
    '0',
    'registry_set_dword',
    'registry_restore_value',
    'Microsoft Learn — Diagnostic data policy (AllowTelemetry)'
),
(
    'opt-disable-gamebar-capture',
    'Desativar captura em segundo plano do Xbox Game Bar',
    'gaming',
    'Impede que o Game Bar grave em segundo plano continuamente durante jogos.',
    'Liberar CPU/GPU/disco usados pela gravação contínua em segundo plano.',
    'Menos overhead de captura; funcionalidades de replay instantâneo do Game Bar ficam indisponíveis.',
    'advanced', 0, 0,
    'HKEY_CURRENT_USER\SOFTWARE\Microsoft\GameBar',
    'AppCaptureEnabled',
    'REG_DWORD',
    '0',
    'registry_set_dword',
    'registry_restore_value',
    'Microsoft Learn — Game Bar background recording policy'
),
(
    'opt-disable-sysmain',
    'Desativar SysMain (Superfetch)',
    'service',
    'Muda o serviço SysMain (pré-carregamento de apps na RAM) para desativado.',
    'Reduzir uso de disco/RAM em segundo plano, especialmente relevante em SSDs.',
    'Menos I/O de disco ocioso; primeira abertura de apps pode ficar levemente mais lenta sem o cache pré-carregado.',
    'advanced', 1, 0,
    'SysMain', NULL, NULL, 'Disabled',
    'service_set_start_type',
    'service_restore_start_type',
    'Microsoft Learn — SysMain service (ex-Superfetch)'
),
(
    'opt-disable-diagtrack',
    'Desativar Connected User Experiences and Telemetry (DiagTrack)',
    'service',
    'Muda o serviço DiagTrack (coleta e envio de telemetria) para desativado.',
    'Reduzir atividade de rede/CPU em segundo plano dedicada à telemetria.',
    'Menos atividade de rede em segundo plano.',
    'advanced', 1, 0,
    'DiagTrack', NULL, NULL, 'Disabled',
    'service_set_start_type',
    'service_restore_start_type',
    'Microsoft Learn — Connected User Experiences and Telemetry service'
),
(
    'opt-disable-compat-appraiser-task',
    'Desativar tarefa de telemetria de compatibilidade de apps',
    'scheduled_task',
    'Desativa a tarefa agendada "Microsoft Compatibility Appraiser", que varre apps instalados para telemetria de compatibilidade.',
    'Reduzir varreduras periódicas de disco/CPU em segundo plano.',
    'Menos picos de CPU/disco periódicos; sem efeito em atualizações normais do Windows.',
    'advanced', 1, 0,
    '\Microsoft\Windows\Application Experience\Microsoft Compatibility Appraiser',
    NULL, NULL, NULL,
    'scheduled_task_disable',
    'scheduled_task_restore',
    'Microsoft Learn — Application Experience scheduled tasks'
),
(
    'opt-disable-ceip-task',
    'Desativar tarefa do Programa de Melhoria da Experiência (CEIP)',
    'scheduled_task',
    'Desativa a tarefa agendada "Consolidator" do Customer Experience Improvement Program.',
    'Reduzir coleta periódica de dados de uso em segundo plano.',
    'Menos atividade periódica em segundo plano dedicada a telemetria de uso.',
    'advanced', 1, 0,
    '\Microsoft\Windows\Customer Experience Improvement Program\Consolidator',
    NULL, NULL, NULL,
    'scheduled_task_disable',
    'scheduled_task_restore',
    'Microsoft Learn — Customer Experience Improvement Program scheduled tasks'
),
(
    'opt-power-balanced',
    'Plano de energia Equilibrado',
    'power_plan',
    'Ativa o plano de energia Equilibrado do Windows.',
    'Equilíbrio entre desempenho e consumo — recomendado para produtividade e streaming.',
    'Menor consumo/calor que Alto Desempenho, com desempenho ainda adequado para tarefas de produtividade.',
    'safe', 0, 0,
    NULL, NULL, NULL, '381b4222-f694-41f0-9685-ff5bb260df2e',
    'power_set_scheme',
    'power_restore_scheme',
    'powercfg /list (esquema Balanced embutido do Windows)'
),
(
    'opt-power-saver',
    'Plano de energia Economia de energia',
    'power_plan',
    'Ativa o plano de energia de Economia de energia do Windows.',
    'Maximizar autonomia de bateria/reduzir consumo.',
    'Menor consumo de energia; desempenho de CPU/GPU reduzido sob carga.',
    'safe', 0, 0,
    NULL, NULL, NULL, 'a1841308-3541-4fab-bc81-f71556f20b4a',
    'power_set_scheme',
    'power_restore_scheme',
    'powercfg /list (esquema Power saver embutido do Windows)'
),
(
    'sec-disable-hags',
    'Desativar agendamento de GPU acelerado por hardware (HAGS)',
    'security',
    'Desativa o HAGS (Hardware-accelerated GPU Scheduling), recurso que delega parte do agendamento de GPU ao driver.',
    'Em alguns sistemas reduz latência de entrada; em outros piora estabilidade — efeito depende muito do driver/GPU.',
    'Ganho de latência não garantido e varia por hardware; risco de instabilidade de driver de vídeo em alguns sistemas.',
    'experimental', 1, 1,
    'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\GraphicsDrivers',
    'HwSchMode',
    'REG_DWORD',
    '1',
    'registry_set_dword',
    'registry_restore_value',
    'Microsoft Learn — Hardware-accelerated GPU scheduling (HwSchMode)'
);

INSERT INTO compatibility_rules (id, optimization_id, windows_version, build_minimo) VALUES
('cr-17', 'opt-network-throttling-off', '10', 10240),
('cr-18', 'opt-network-throttling-off', '11', 22000),
('cr-19', 'opt-system-responsiveness', '10', 10240),
('cr-20', 'opt-system-responsiveness', '11', 22000),
('cr-21', 'opt-win32-priority-separation', '10', 10240),
('cr-22', 'opt-win32-priority-separation', '11', 22000),
('cr-23', 'opt-games-gpu-priority', '10', 10240),
('cr-24', 'opt-games-gpu-priority', '11', 22000),
('cr-25', 'opt-disable-telemetry-policy', '10', 10240),
('cr-26', 'opt-disable-telemetry-policy', '11', 22000),
('cr-27', 'opt-disable-gamebar-capture', '10', 17134),
('cr-28', 'opt-disable-gamebar-capture', '11', 22000),
('cr-29', 'opt-disable-sysmain', '10', 10240),
('cr-30', 'opt-disable-sysmain', '11', 22000),
('cr-31', 'opt-disable-diagtrack', '10', 10240),
('cr-32', 'opt-disable-diagtrack', '11', 22000),
('cr-33', 'opt-disable-compat-appraiser-task', '10', 10240),
('cr-34', 'opt-disable-compat-appraiser-task', '11', 22000),
('cr-35', 'opt-disable-ceip-task', '10', 10240),
('cr-36', 'opt-disable-ceip-task', '11', 22000),
('cr-37', 'opt-power-balanced', '10', 10240),
('cr-38', 'opt-power-balanced', '11', 22000),
('cr-39', 'opt-power-saver', '10', 10240),
('cr-40', 'opt-power-saver', '11', 22000),
('cr-41', 'sec-disable-hags', '10', 19041),
('cr-42', 'sec-disable-hags', '11', 22000);
